### ISSUE TITLE
exception в game:info

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1651]
1-ое

```
[ERROR 2015-06-10 12:41:21,184 workers 25905] Exception in worker "<the_tale.game.workers.logic.Worker object at 0x7f41e560ac90>"
Traceback (most recent call last):
  File "/home/tie/repos/mine/dext/dext/common/amqp_queues/workers.py", line 143, in process_cmd
    cmd(**cmd_data)
  File "/home/tie/repos/mine/the-tale/the_tale/game/workers/logic.py", line 118, in process_register_account
    self.storage.load_account_data(account)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 40, in load_account_data
    self._add_hero(hero)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 88, in _add_hero
    self.add_action(action)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 131, in add_action
    self.add_meta_action(get_meta_action_by_model(MetaAction.objects.get(id=action.meta_action_id)))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: MetaAction matching query does not exist.
```

2-ое
 
```
Internal Server Error: /game/api/info
Traceback (most recent call last):
  File "/home/the-tale/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/the-tale/env/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/the-tale/env/lib/python2.7/site-packages/dext/common/utils/views.py", line 71, in __call__
    response = self.logic(context)
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/views.py", line 334, in api_info
    client_turns=context.client_turns)
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/logic.py", line 197, in form_game_info
    client_turns=client_turns)
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/logic.py", line 160, in _form_game_account_info
    for_last_turn=(not is_own))
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/heroes/prototypes.py", line 688, in cached_ui_info_for_hero
    data = hero.ui_info(actual_guaranteed=False)
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/heroes/prototypes.py", line 619, in ui_info
    'action': self.actions.current_action.ui_info(),
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/actions/prototypes.py", line 205, in ui_info
    self.description = self.get_description()
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/actions/prototypes.py", line 274, in get_description
    return linguistics_logic.get_text(self.description_text_name, self.get_description_arguments())
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/actions/prototypes.py", line 1902, in description_text_name
    return self.meta_action.description_text_name
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/actions/prototypes.py", line 234, in meta_action
    return meta_actions.get_meta_action_by_id(self.meta_action_id) if self.meta_action_id is not None else None
  File "/home/the-tale/env/lib/python2.7/site-packages/the_tale/game/actions/meta_actions.py", line 48, in get_meta_action_by_id
    return get_meta_action_by_model(MetaAction.objects.get(id=meta_action_id))
  File "/home/the-tale/env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/the-tale/env/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: MetaAction matching query does not exist.

Request repr():
<WSGIRequest
path:/game/api/info,
GET:<QueryDict: {u'api_client': [u'the_tale-v0.3.19.2'], u'_': [u'1433547771232'], u'api_version': [u'1.3']}>,
POST:<QueryDict: {}>,
COOKIES:{'__atuvc': '33%7C21%2C47%7C22',
 '__atuvs': '557233f582e351dc001',
 '_ga': 'GA1.2.1808459318.1432842575',
 '_gat': '1',
 'csrftoken': 'QdNVMewefgbgVzZqlzFacCyQ6Dcyrgsc',
 'sessionid': 'b3k1sj2gnzdqussq3470foxlcmkw7aol'},
META:{u'CSRF_COOKIE': u'QdNVMewefgbgVzZqlzFacCyQ6Dcyrgsc',
 u'CSRF_COOKIE_USED': True,
 'DOCUMENT_ROOT': '/etc/apache2/htdocs',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'ru,uk;q=0.8,en;q=0.6',
 'HTTP_CONNECTION': 'close',
 'HTTP_COOKIE': 'sessionid=b3k1sj2gnzdqussq3470foxlcmkw7aol; _gat=1; csrftoken=QdNVMewefgbgVzZqlzFacCyQ6Dcyrgsc; _ga=GA1.2.1808459318.1432842575; __atuvc=33%7C21%2C47%7C22; __atuvs=557233f582e351dc001',
 'HTTP_HOST': 'the-tale.org',
 'HTTP_REFERER': 'http://the-tale.org/game/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 YaBrowser/15.4.2272.3716 Safari/537.36',
 'HTTP_X_CSRFTOKEN': 'QdNVMewefgbgVzZqlzFacCyQ6Dcyrgsc',
 'HTTP_X_FORWARDED_FOR': '78.111.215.133',
 'HTTP_X_NEWRELIC_ID': 'XQYBWVdADgQDUFlT',
 'HTTP_X_REAL_IP': '78.111.215.133',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'PATH_INFO': u'/game/api/info',
 'PATH_TRANSLATED': '/home/the-tale/conf/wsgi.py/game/api/info',
 'QUERY_STRING': 'api_client=the_tale-v0.3.19.2&api_version=1.3&_=1433547771232',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '58376',
 'REQUEST_METHOD': 'GET',
 'REQUEST_URI': '/game/api/info?api_client=the_tale-v0.3.19.2&api_version=1.3&_=1433547771232',
 'SCRIPT_FILENAME': '/home/the-tale/conf/wsgi.py',
 'SCRIPT_NAME': u'',
 'SERVER_ADDR': '127.0.0.1',
 'SERVER_ADMIN': '[no address given]',
 'SERVER_NAME': 'the-tale.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.0',
 'SERVER_SIGNATURE': '<address>Apache/2.2.22 (Ubuntu) Server at the-tale.org Port 80</address>\n',
 'SERVER_SOFTWARE': 'Apache/2.2.22 (Ubuntu)',
 'mod_wsgi.application_group': 'localhost|',
 'mod_wsgi.callable_object': 'application',
 'mod_wsgi.handler_script': '',
 'mod_wsgi.input_chunked': '0',
 'mod_wsgi.listener_host': '',
 'mod_wsgi.listener_port': '8080',
 'mod_wsgi.process_group': 'the-tale.org',
 'mod_wsgi.request_handler': 'wsgi-script',
 'mod_wsgi.script_reloading': '1',
 'mod_wsgi.version': (3, 3),
 'wsgi.errors': <mod_wsgi.Log object at 0x7ff2f6eceef0>,
 'wsgi.file_wrapper': <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7ff2f04de738>,
 'wsgi.input': <newrelic.api.web_transaction._WSGIInputWrapper object at 0x7ff2f05e4050>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 1)}>
```

**Comment by Tiendil** [comment]
2-ое возможно из-за того, что LogicStorage.remove_action вызывает удаление MetaAction при своём вызове, а сама информация о героях сохраняется позже. В итоге у нас есть промежуток времени, в котором модели уже нет, но сохранённые записи героев на неё ещё ссылаются

**Comment by Tiendil** [comment]
Поскольку объём информации в meta action небольшой, в памяти оно требоуется только в одном рабочем (поскольку всегда относится только к одному bundl-у), то хранить её в отдельной модели не надо.

Её копию можно хранить в записи каждого героя, а при инициализации поддымать первую попавшуюся.
