### ISSUE TITLE
PvP: исключение в мета-действии

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/the-tale#1661]
```
[ERROR 2015-06-10 12:41:21,184 workers 25905] Exception in worker "<the_tale.game.workers.logic.Worker object at 0x7f41e560ac90>"
Traceback (most recent call last):
  File "/home/tie/repos/mine/dext/dext/common/amqp_queues/workers.py", line 143, in process_cmd
    cmd(**cmd_data)
  File "/home/tie/repos/mine/the-tale/the_tale/game/workers/logic.py", line 118, in process_register_account
    self.storage.load_account_data(account)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 40, in load_account_data
    self._add_hero(hero)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 88, in _add_hero
    self.add_action(action)
  File "/home/tie/repos/mine/the-tale/the_tale/game/logic_storage.py", line 131, in add_action
    self.add_meta_action(get_meta_action_by_model(MetaAction.objects.get(id=action.meta_action_id)))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: MetaAction matching query does not exist.
```

**Comment by Tiendil** [comment]
Закрыто в польщу gh-1651
